import { Leaf, BookOpen, Palette, Stethoscope, Users } from 'lucide-react'
import type { Category } from '../types'

export const CATEGORY_ICONS: Record<Exclude<Category, 'All'>, React.ReactNode> = {
  Environment: <Leaf size={14} />,
  Education: <BookOpen size={14} />,
  Health: <Stethoscope size={14} />,
  Arts: <Palette size={14} />,
  Community: <Users size={14} />,
}

export const CATEGORY_COLORS: Record<Exclude<Category, 'All'>, string> = {
  Environment: 'bg-emerald-100 text-emerald-800',
  Education: 'bg-sky-100 text-sky-800',
  Health: 'bg-rose-100 text-rose-800',
  Arts: 'bg-violet-100 text-violet-800',
  Community: 'bg-amber-100 text-amber-800',
}

export const SEED_EVENTS = [
  {
    title: 'Youth Leadership Workshop Series',
    category: 'Education' as const,
    location: 'Brooklyn, NY',
    commitment: '4 hrs/week',
    spots: 12,
    description: 'Facilitate weekly workshops empowering teens with public speaking, civic engagement, and leadership skills. Ideal for educators and community organizers.',
    skills: ['Facilitation', 'Youth Development', 'Public Speaking'],
    image: 'https://images.pexels.com/photos/5905445/pexels-photo-5905445.jpeg?auto=compress&cs=tinysrgb&w=800',
    company_email: 'contact@higherfire.org',
    company_name: 'Higher Fire',
  },
  {
    title: 'Urban Reforestation Crew',
    category: 'Environment' as const,
    location: 'Queens, NY',
    commitment: '6 hrs/month',
    spots: 20,
    description: 'Join weekend planting crews to restore urban green spaces. No experience needed — just bring gloves and a willingness to dig!',
    skills: ['Physical Stamina', 'Teamwork'],
    image: 'https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&w=800',
    company_email: 'info@greencityalliance.org',
    company_name: 'GreenCity Alliance',
  },
  {
    title: 'Adult Literacy Tutor',
    category: 'Education' as const,
    location: 'Harlem, NY',
    commitment: '2 hrs/week',
    spots: 8,
    description: 'Tutor adults working toward their GED or basic literacy skills. Training provided. Make a lasting impact on someone\'s future.',
    skills: ['Patience', 'Communication', 'Teaching'],
    image: 'https://images.pexels.com/photos/1367269/pexels-photo-1367269.jpeg?auto=compress&cs=tinysrgb&w=800',
    company_email: 'volunteer@openpages.org',
    company_name: 'Open Pages Foundation',
  },
  {
    title: 'Community Health Fair Support',
    category: 'Health' as const,
    location: 'Bronx, NY',
    commitment: '1 day event',
    spots: 15,
    description: 'Assist at our annual health fair — welcome visitors, distribute resources, and guide attendees to screenings and services.',
    skills: ['Customer Service', 'Organization'],
    image: 'https://images.pexels.com/photos/3825586/pexels-photo-3825586.jpeg?auto=compress&cs=tinysrgb&w=800',
    company_email: 'events@bronxhealth.org',
    company_name: 'Bronx Community Health',
  },
  {
    title: 'Mural Project Assistant',
    category: 'Arts' as const,
    location: 'Lower East Side, NY',
    commitment: '3 hrs/week',
    spots: 6,
    description: 'Help local artists create murals celebrating neighborhood history. No art experience required — roles include prep, painting, and community outreach.',
    skills: ['Creativity', 'Community Outreach'],
    image: 'https://images.pexels.com/photos/1053687/pexels-photo-1053687.jpeg?auto=compress&cs=tinysrgb&w=800',
    company_email: 'studio@lesarts.org',
    company_name: 'LES Arts Collective',
  },
  {
    title: 'Neighborhood Clean-Up',
    category: 'Community' as const,
    location: 'Flatbush, Brooklyn',
    commitment: 'Monthly Saturday',
    spots: 30,
    description: 'Join us every last Saturday to clean parks and streets in Flatbush. A great way to meet neighbors and take pride in your community.',
    skills: ['Physical Activity', 'Teamwork'],
    image: 'https://images.pexels.com/photos/2990644/pexels-photo-2990644.jpeg?auto=compress&cs=tinysrgb&w=800',
    company_email: 'contact@higherfire.org',
    company_name: 'Higher Fire',
  },
]
